export const instrumentOptions = [
    { value: 'balalajka', label: 'Balalajka' },
    { value: 'basszusgitar', label: 'Basszusgitár' },
    { value: 'banjo', label: 'Banjo' },
    { value: 'bracsa', label: 'Brácsa' },
    { value: 'buzuki', label: 'Buzuki' },
    { value: 'cajon', label: 'Cajón' },
    { value: 'cegledi-kanna', label: 'Ceglédi kanna' },
    { value: 'cimbalom', label: 'Cimbalom' },
    { value: 'citera', label: 'Citera' },
    { value: 'csello', label: 'Cselló' },
    { value: 'didgeridoo', label: 'Didgeridoo' },
    { value: 'dob', label: 'Dob' },
    { value: 'doromb', label: 'Doromb' },
    { value: 'duda', label: 'Duda' },
    { value: 'fagott', label: 'Fagott' },
    { value: 'furulya', label: 'Furulya' },
    { value: 'fuvola', label: 'Fuvola' },
    { value: 'gitar', label: 'Gitár' },
    { value: 'harmonika', label: 'Harmonika' },
    { value: 'harfa', label: 'Hárfa' },
    { value: 'harsona', label: 'Harsona' },
    { value: 'hegedu', label: 'Hegedű' },
    { value: 'kalimba', label: 'Kalimba' },
    { value: 'kasztanyetta', label: 'Kasztanyetta' },
    { value: 'klarinet', label: 'Klarinét' },
    { value: 'konga', label: 'Konga' },
    { value: 'kurt', label: 'Kürt' },
    { value: 'lant', label: 'Lant' },
    { value: 'magyar-duda', label: 'Magyar duda' },
    { value: 'mandolin', label: 'Mandolin' },
    { value: 'marimba', label: 'Marimba' },
    { value: 'nagybogo', label: 'Nagybőgő' },
    { value: 'oboa', label: 'Oboa' },
    { value: 'orgona', label: 'Orgona' },
    { value: 'pansip', label: 'Pánsíp' },
    { value: 'piccolo', label: 'Piccolo' },
    { value: 'skot-duda', label: 'Skót duda' },
    { value: 'szajharmonika', label: 'Szájharmonika' },
    { value: 'szaxofon', label: 'Szaxofon' },
    { value: 'szintetizator', label: 'Szintetizátor' },
    { value: 'szitar', label: 'Szitár' },
    { value: 'trombita', label: 'Trombita' },
    { value: 'tuba', label: 'Tuba' },
    { value: 'ukulele', label: 'Ukulele' },
    { value: 'vibrafon', label: 'Vibrafon' },
    { value: 'xilofon', label: 'Xilofon' },
    { value: 'zongora', label: 'Zongora' },
    { value: 'enek', label: 'Ének' },
    { value: 'egyeb', label: 'Egyéb' },
];