// generateSettlements.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// emulate __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// paths
const csvPath = path.join(__dirname, 'telepulesekRaw.csv');
const outPath = path.join(__dirname, 'settlements.js');

// read & parse CSV, drop header & county column
const raw = fs.readFileSync(csvPath, 'utf8');
const lines = raw.trim().split('\n').slice(1);

const options = lines.map(line => {
    const [helyseg/*, county*/] = line.split(';').map(s => s.trim());
    const slug = helyseg
        .normalize('NFD')                    // decompose accents
        .replace(/[\u0300-\u036f]/g, '')     // strip diacritics
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')         // non-alnum → hyphen
        .replace(/(^-|-$)/g, '');            // trim stray hyphens
    return { value: slug, label: helyseg };
});

// build JS module text
const outLines = [];
outLines.push('// AUTO-GENERATED by generateSettlements.mjs');
outLines.push('export const settlements = [');
options.forEach(o => {
    outLines.push(`  { value: '${o.value}', label: '${o.label}' },`);
});
outLines.push('];\n');

// write it out
fs.writeFileSync(outPath, outLines.join('\n'), 'utf8');
console.log(`Wrote ${options.length} entries to ${outPath}`);
