/*
futtatáshoz parancs:

node settlementsGenerate.mjs

*/

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const csvPath = path.join(__dirname, 'telepulesekRaw.csv');
const outPath = path.join(__dirname, 'settlements.js');

const raw = fs.readFileSync(csvPath, 'utf8');
const lines = raw.trim().split('\n').slice(1);

const options = lines.map(line => {
    const [helyseg/*, county*/] = line.split(';').map(s => s.trim());
    const slug = helyseg
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
    return { value: slug, label: helyseg };
});

const outLines = [];
outLines.push('// AUTO-GENERATED by generateSettlements.mjs');
outLines.push('export const settlements = [');
options.forEach(o => {
    outLines.push(`  { value: '${o.value}', label: '${o.label}' },`);
});
outLines.push('];\n');

fs.writeFileSync(outPath, outLines.join('\n'), 'utf8');
console.log(`Wrote ${options.length} entries to ${outPath}`);
